version: '3.6'
services:


  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  vimond-api:
    # env_file:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/vimond-api
    command: npm start
    working_dir: /usr/src/vimond-api
    ports:
      - "8040:8040"
    environment:
      REDIS_URI: redis://redis:6379
